In [279]:
import funcoes
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.feature.texture import greycomatrix
import statistics
import pandas as pd

In [9]:
#Verificar as imagens
image1 = cv2.imread("Brodatz128x128(Tex)/c001_001.png")
image1

array([[[117, 117, 117],
        [ 69,  69,  69],
        [204, 204, 204],
        ...,
        [225, 225, 225],
        [218, 218, 218],
        [196, 196, 196]],

       [[106, 106, 106],
        [ 69,  69,  69],
        [204, 204, 204],
        ...,
        [231, 231, 231],
        [220, 220, 220],
        [199, 199, 199]],

       [[110, 110, 110],
        [ 71,  71,  71],
        [206, 206, 206],
        ...,
        [226, 226, 226],
        [218, 218, 218],
        [191, 191, 191]],

       ...,

       [[145, 145, 145],
        [ 64,  64,  64],
        [188, 188, 188],
        ...,
        [163, 163, 163],
        [161, 161, 161],
        [151, 151, 151]],

       [[146, 146, 146],
        [ 66,  66,  66],
        [187, 187, 187],
        ...,
        [171, 171, 171],
        [168, 168, 168],
        [147, 147, 147]],

       [[145, 145, 145],
        [ 66,  66,  66],
        [192, 192, 192],
        ...,
        [184, 184, 184],
        [160, 160, 160],
        [152, 152, 152]]], dtype=uint8)

In [10]:
image1.shape

(128, 128, 3)

In [39]:
#DÃºvida
print(image1[:128,127,0])
print(image1[:128,127,1])
print(image1[:128,127,2])

[196 199 191 190 193 201 198 195 193 185 186 191 193 196 198 186  82  40
 107 204 220 215 201 190 190 187 190 178 178 173 180 187 182 183 176 173
 163 161 160 163 164 171 173 171 179 161 121 112 176 216 222 210 175 163
 169 162 165 164 154 159 161 167 161 171 170 164 163 160 153 159 162 164
 169 159 152 152 159 160 160 172 148  81  51 148 211 215 209 181 165 173
 174 164 166 166 162 156 151 151 164 171 178 183 167 160 163 174 167 160
 156 150 141  82  88 189 211 211 201 165 154 160 150 150 149 152 151 151
 147 152]
[196 199 191 190 193 201 198 195 193 185 186 191 193 196 198 186  82  40
 107 204 220 215 201 190 190 187 190 178 178 173 180 187 182 183 176 173
 163 161 160 163 164 171 173 171 179 161 121 112 176 216 222 210 175 163
 169 162 165 164 154 159 161 167 161 171 170 164 163 160 153 159 162 164
 169 159 152 152 159 160 160 172 148  81  51 148 211 215 209 181 165 173
 174 164 166 166 162 156 151 151 164 171 178 183 167 160 163 174 167 160
 156 150 141  82  88 189 211 211 201 165 154 160 150 150 149 152 151 151
 147 152]
[196 199 191 190 193 201 198 195 193 185 186 191 193 196 198 186  82  40
 107 204 220 215 201 190 190 187 190 178 178 173 180 187 182 183 176 173
 163 161 160 163 164 171 173 171 179 161 121 112 176 216 222 210 175 163
 169 162 165 164 154 159 161 167 161 171 170 164 163 160 153 159 162 164
 169 159 152 152 159 160 160 172 148  81  51 148 211 215 209 181 165 173
 174 164 166 166 162 156 151 151 164 171 178 183 167 160 163 174 167 160
 156 150 141  82  88 189 211 211 201 165 154 160 150 150 149 152 151 151
 147 152]

In [122]:
imagens = []

In [123]:
#Carregar as 1776 imagens
z = 0
for i in range(2):
    for j in range(10):
        for l in range (10):
            
            for m in range(2):
                for n in range(10):
                    
                    a = int(f'{m}{n}')
                    b = int(f'{i}{j}{l}')

                    if a > 16 or b > 111 or (n == 0 and m == 0) or (i== 0 and j == 0 and l == 0):
                        pass
                    else:
                        #print('c{}{}{}_0{}{}.png'.format(i,j,l, m,n))
                        image_aux = cv2.imread("Brodatz128x128(Tex)/c{}{}{}_0{}{}.png".format(i,j,l,m,n))
                        imagens.append(image_aux[:128,:128,0])
                        z +=1
                    
print(z)

1776

In [303]:
#print(a.ravel())transforma em um vetor a matriz
soma = []
media = []
minimo = []
traco = []
maximo = []
desvio = []
pico_a_pico = []

for i in range(len(imagens)):
    a = imagens[i]
    soma.append(a.sum())
    media.append(a.mean())
    minimo.append(a.min())
    traco.append(a.trace())
    maximo.append(a.max())
    desvio.append(a.std())
    pico_a_pico.append(a.ptp())

In [304]:
k = []
for i in range(1,112):
    for j in range(1,17):
        k.append(i)

In [305]:
colunas = [soma,media,minimo,traco,maximo,desvio,pico_a_pico,k]
save_arq = pd.DataFrame(colunas)
save_arq = save_arq.transpose()
save_arq

              0           1     2        3      4          5      6      7
0     2701965.0  164.914856   0.0  21832.0  234.0  40.972874  234.0    1.0
1     2662250.0  162.490845   0.0  19939.0  239.0  41.444281  239.0    1.0
2     2675056.0  163.272461  11.0  21791.0  247.0  40.026363  236.0    1.0
3     2636329.0  160.908752   3.0  20065.0  244.0  41.869256  241.0    1.0
4     2746729.0  167.647034   0.0  22405.0  232.0  42.044422  232.0    1.0
...         ...         ...   ...      ...    ...        ...    ...    ...
1771  3116548.0  190.218994   6.0  23860.0  244.0  41.738077  238.0  111.0
1772  2324972.0  141.905029   0.0  18424.0  235.0  51.866312  235.0  111.0
1773  2566184.0  156.627441   0.0  17939.0  229.0  47.699495  229.0  111.0
1774  2634853.0  160.818665   4.0  19521.0  230.0  44.579016  226.0  111.0
1775  3032972.0  185.117920   6.0  23488.0  235.0  38.995339  229.0  111.0

[1776 rows x 8 columns]

In [306]:
save_arq.to_csv("matrix.csv")